export const STRATEGY_LIBRARY = [
  {
    key: "nqkz",
    name: "NQ London Kill Zone Breakout",
    symbol: "NAS100",
    timeframe: "M5",
    entry: "Kill Zone Breakout",
    rr: "1:2",
    rules: "03:00–09:30 ET range build. Entry on M5 closed-candle breakout beyond Kill Zone high/low with body ≥ 5 pts and wick ≤ 0.6× body. ATR filter confirms volatility. Fixed 1:2 RR, break-even at 1R, no recovery positions.",
  },
  {
    key: "msbos",
    name: "Market Structure BOS Retest",
    symbol: "XAUUSD",
    timeframe: "M5",
    entry: "BOS Retest",
    rr: "1:2",
    rules: "H1 structure mapping → M5 Break of Structure → retest within 10 pts of broken level → confirmation candle. Fixed 1:2 RR, break-even at 1R, no indicators.",
  },
  {
    key: "gdb",
    name: "Gold Daily Breakout",
    symbol: "XAUUSD",
    timeframe: "D1",
    entry: "Previous Day Breakout",
    rr: "1:2",
    rules: "Previous-day high/low breakout via OCO pending stops. Max 1 trade/day. ATR filter + break-even at 1R + trailing after 1R. Cancel unfilled orders at session end.",
  },
  {
    key: "smc",
    name: "SMC Liquidity Sweep",
    symbol: "XAUUSD",
    timeframe: "M5",
    entry: "Liquidity Sweep",
    rr: "1:2",
    rules: "HTF (M15) 200 EMA trend gate. M1 entry after liquidity sweep + RSI exhaustion (80/20). VWAP + session filter. No entries within 10 min of high-impact news.",
  },
  {
    key: "swing",
    name: "Swing Trend Pullback",
    symbol: "XAUUSD",
    timeframe: "M15",
    entry: "Trend Pullback",
    rr: "1:2",
    rules: "M15 EMA 20/50 trend. Pullback into 0.25 ATR zone of EMA 20. Engulfing confirmation. ATR-scaled SL (1.5×), min 1:2 RR. Break-even at 1R, partial close 50%.",
  },
  {
    key: "hybrid",
    name: "Hybrid Confluence Mode",
    symbol: "XAUUSD",
    timeframe: "M15",
    entry: "Confluence",
    rr: "1:2",
    rules: "EMA 6/25 trend + EMA 20 pullback zone + SMC liquidity sweep merged as scored layers. Min confluence score 80/100. Capped recovery (1.25× max). ATR SL 1.5–1.8×, basket TP.",
  },
];

export const ALERT_TEMPLATE = `{
  "secret": "{{WEBHOOK_SECRET}}",
  "symbol": "{{ticker}}",
  "action": "{{strategy.order.action}}",
  "lot": 0.01,
  "sl": 0,
  "tp": 0,
  "strategy": "{{strategy.title}}",
  "timeframe": "{{interval}}",
  "comment": "TradingView signal"
}`;