export const STRATEGIES = [
  "Momentum Scalping",
  "Range Breakout",
  "Volatility Spike",
  "Hybrid Manual",
  "HFT Scalper",
  "Grid Trading",
  "Liquidity Sweep Scalping",
  "Hedge Scalper",
  "Swing Trend Pullback Continuation 2026",
  "EMA Trend Progressive Recovery",
  "Hybrid Confluence Mode",
  "NQ London Kill Zone Breakout",
  "Market Structure BOS Retest Scalper",
  "Orderflow Opening Range Breakout",
  "Gold Morning Range Breakout",
  "Gold Daily Breakout",
  "Auto (AI Select)",
];

export const PAIRS = ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "NAS100", "US30", "BTCUSD"];
export const MODES = ["Conservative", "Balanced", "Aggressive"];
export const MENTALITIES = ["Basic", "Premium"];

// Aggressive = more concurrent trades + bigger lots. Conservative = fewer trades + smaller lots.
export const MODE_PRESETS = {
  Conservative: { max_concurrent_trades: 1, lot_size: 0.01 },
  Balanced:     { max_concurrent_trades: 2, lot_size: 0.02 },
  Aggressive:   { max_concurrent_trades: 5, lot_size: 0.05, risk_percentage: 5, stop_after_losses: 5, daily_loss_limit: 100 },
};

export const DEFAULT = {
  symbol: "XAUUSD",
  strategy: "Auto (AI Select)",
  trading_mode: "Balanced",
  bot_mentality: "Premium",
  trade_direction: "both",
  // Lot & Risk
  lot_size: 0.03,
  max_concurrent_trades: 2,
  risk_percentage: 2,
  lot_multiplier: 2,
  multiplier_min_equity_ratio: 2,
  auto_multiplier_enabled: false,
  // SL / TP
  stop_loss: 20,
  take_profit: 40,
  dynamic_stop_loss: false,
  atr_sl_multiplier: 2,
  // Daily limits
  max_daily_trades: 999999,
  stop_after_losses: 2,
  daily_profit_target: 200,
  daily_loss_limit: 20,
  // Daily Profit Target
  daily_profit_target_enabled: true,
  daily_profit_target_amount: 200,
  daily_profit_target_mode: "Fixed",
  session_cooldown_minutes: 60,
  daily_profit_target_percent: 0,
  stop_trading_at_daily_target: true,
  // HFT Scalper specific
  hft_max_trades: 15,
  hft_burst_points: 8,
  hft_basket_tp_pts: 60,
  hft_stop_loss_pts: 150,
  hft_use_break_even: true,
  hft_be_trigger: 20,
  hft_be_lock: 3,
  hft_trailing_dist: 15,
  hft_max_spread: 20,
  hft_ma_period: 20,
  // Grid Trading specific
  grid_distance_pips: 10,
  grid_max_levels: 5,
  // Liquidity Sweep Scalping specific
  liq_htf_timeframe: "M15",
  liq_entry_timeframe: "M1",
  liq_htf_ema_period: 200,
  liq_rsi_overbought: 80,
  liq_rsi_oversold: 20,
  liq_use_vwap: true,
  liq_session_only: true,
  liq_news_buffer_minutes: 10,
  // Equity Guard
  equity_guard_enabled: true,
  equity_guard_min_equity_pct: 75,
  // Trend Filter
  trend_filter_enabled: true,
  trend_filter_timeframe: "M15",
  trend_filter_ema_period: 200,
  // Auto Schedule
  auto_start_enabled: false,
  auto_start_time: "09:00",
  auto_stop_enabled: true,
  // Hedge Scalper
  hedge_scalp_tp_pips: 30,
  hedge_scalp_sl_pips: 15,
  hedge_scalp_lot_size: 0.02,
  hedge_scalp_max_pairs: 3,
  hedge_scalp_close_winner_on_sl: true,
  hedge_scalp_reopen_delay_sec: 5,
  hedge_scalp_trend_entry: true,
  hedge_scalp_trend_timeframe: "M15",
  hedge_scalp_trend_ema_period: 200,
  hedge_scalp_hedge_mode: "Same Pair",
  hedge_scalp_hedge_trigger_pips: 15,
  hedge_scalp_scalp_over_hedge: true,
  hedge_scalp_scalp_tp_pips: 5,
  hedge_scalp_drawdown_reduction: true,
  hedge_scalp_dd_close_ratio: 1,
  hedge_scalp_pair_priority: true,
  hedge_scalp_priority_lookback_trades: 20,
  // Swing Trend Pullback Continuation 2026
  swing_timeframe: "M15",
  swing_ema_fast: 20,
  swing_ema_slow: 50,
  swing_atr_period: 14,
  swing_atr_sl_multiplier: 1.5,
  swing_min_rr: 2,
  swing_lot_size: 0.01,
  swing_max_open_trades: 2,
  swing_max_trades_per_day: 3,
  swing_max_consecutive_losses: 2,
  swing_cooldown_hours: 8,
  swing_max_daily_loss_pct: 2,
  swing_max_daily_drawdown_pct: 3,
  swing_max_spread_points: 30,
  swing_use_break_even: true,
  swing_be_at_r: 1,
  swing_use_trailing: false,
  swing_trailing_atr_mult: 1.5,
  swing_pullback_zone_atr: 0.25,
  swing_block_deep_pullback: true,
  swing_partial_close_50: true,
  // EMA Trend Progressive Recovery
  tpr_ema_fast: 6,
  tpr_ema_slow: 25,
  tpr_atr_period: 14,
  tpr_min_ema_distance: 0,
  tpr_trend_strength: 0,
  tpr_lot_size: 0.01,
  tpr_max_open_positions: 2,
  tpr_max_recovery_positions: 1,
  tpr_lot_multiplier: 1.0,
  tpr_max_lot_multiplier: 1.25,
  tpr_recovery_atr_mult: 1.2,
  tpr_basket_profit_target: 10,
  tpr_emergency_sl_atr: 1.8,
  tpr_equity_stop_pct: 3,
  tpr_daily_loss_limit_pct: 2,
  tpr_max_trades_per_day: 3,
  tpr_max_consecutive_losses: 2,
  tpr_cooldown_hours: 8,
  tpr_use_break_even: true,
  tpr_partial_close_50: true,
  tpr_min_rr: 2,
  tpr_max_spread_points: 30,
  // Hybrid Confluence Mode
  hybrid_timeframe: "M15",
  hybrid_ema_6: 6,
  hybrid_ema_20: 20,
  hybrid_ema_25: 25,
  hybrid_ema_50: 50,
  hybrid_atr_period: 14,
  hybrid_min_ema_distance: 0,
  hybrid_min_atr: 0,
  hybrid_pullback_zone_atr: 0.25,
  hybrid_max_pullback_depth_atr: 0.5,
  hybrid_swing_lookback: 20,
  hybrid_require_engulfing: true,
  hybrid_lot_size: 0.01,
  hybrid_max_positions: 2,
  hybrid_max_recovery_positions: 1,
  hybrid_lot_multiplier: 1.0,
  hybrid_max_lot_multiplier: 1.25,
  hybrid_recovery_atr_mult: 1.2,
  hybrid_sl_atr_min: 1.5,
  hybrid_sl_atr_max: 1.8,
  hybrid_min_rr: 2,
  hybrid_use_break_even: true,
  hybrid_partial_close_50: true,
  hybrid_max_trades_per_day: 3,
  hybrid_max_consecutive_losses: 2,
  hybrid_cooldown_hours: 8,
  hybrid_max_daily_loss_pct: 2,
  hybrid_equity_stop_pct: 3,
  hybrid_max_spread_points: 30,
  hybrid_min_score: 80,
  hybrid_score_trend: 30,
  hybrid_score_pullback: 20,
  hybrid_score_sweep: 30,
  hybrid_score_engulfing: 10,
  hybrid_score_filters: 10,
  // NQ London Kill Zone Breakout
  nqkz_lot_size: 0.01,
  nqkz_max_open_trades: 1,
  nqkz_max_trades_per_day: 2,
  nqkz_risk_reward: 2,
  nqkz_sl_buffer_points: 5,
  nqkz_breakout_buffer_points: 2,
  nqkz_min_body_points: 5,
  nqkz_max_wick_body_ratio: 0.6,
  nqkz_min_range_points: 20,
  nqkz_max_range_points: 400,
  nqkz_use_atr_filter: true,
  nqkz_atr_period: 14,
  nqkz_min_atr: 0,
  nqkz_use_break_even: true,
  nqkz_partial_close_50: false,
  nqkz_max_spread_points: 30,
  nqkz_max_daily_loss_pct: 2,
  nqkz_equity_stop_pct: 3,
  nqkz_max_consecutive_losses: 2,
  nqkz_cooldown_hours: 8,
  // Market Structure BOS Retest Scalper
  ms_htf_timeframe: "H1",
  ms_entry_timeframe: "M5",
  ms_confirm_timeframe: "M15",
  ms_swing_lookback: 20,
  ms_require_confirmation: true,
  ms_retest_buffer_points: 10,
  ms_lot_size: 0.01,
  ms_max_open_trades: 1,
  ms_max_trades_per_day: 3,
  ms_risk_reward: 2,
  ms_sl_buffer_points: 5,
  ms_use_break_even: true,
  ms_partial_close_50: false,
  ms_max_spread_points: 30,
  ms_max_daily_loss_pct: 2,
  ms_max_daily_drawdown_pct: 3,
  ms_max_consecutive_losses: 2,
  ms_cooldown_hours: 8,
  // Orderflow Opening Range Breakout
  ofor_lot_size: 0.01,
  ofor_max_open_trades: 1,
  ofor_max_trades_per_day: 2,
  ofor_risk_reward: 2,
  ofor_sl_buffer_points: 5,
  ofor_breakout_buffer_points: 2,
  ofor_min_body_points: 5,
  ofor_max_wick_body_ratio: 0.6,
  ofor_min_range_points: 20,
  ofor_max_range_points: 400,
  ofor_require_retest: true,
  ofor_retest_buffer_points: 10,
  ofor_use_orderflow_filter: true,
  ofor_volume_expansion_mult: 1.5,
  ofor_use_atr_filter: true,
  ofor_atr_period: 14,
  ofor_min_atr: 0,
  ofor_use_break_even: true,
  ofor_partial_close_50: false,
  ofor_max_spread_points: 30,
  ofor_max_daily_loss_pct: 2,
  ofor_equity_stop_pct: 3,
  ofor_max_consecutive_losses: 2,
  ofor_cooldown_hours: 8,
  // Gold Morning Range Breakout
  gmr_lot_size: 0.01,
  gmr_max_open_trades: 1,
  gmr_max_trades_per_day: 2,
  gmr_risk_reward: 2,
  gmr_sl_buffer_points: 5,
  gmr_min_body_points: 5,
  gmr_min_range_points: 20,
  gmr_max_range_points: 400,
  gmr_require_retest: true,
  gmr_retest_buffer_points: 10,
  gmr_use_volume_filter: true,
  gmr_volume_threshold_mult: 1,
  gmr_use_atr_filter: true,
  gmr_atr_period: 14,
  gmr_min_atr: 0,
  gmr_use_news_filter: true,
  gmr_use_break_even: true,
  gmr_partial_close_50: false,
  gmr_max_spread_points: 30,
  gmr_max_daily_loss_pct: 2,
  gmr_equity_stop_pct: 3,
  gmr_max_consecutive_losses: 2,
  gmr_cooldown_hours: 8,
  // Gold Daily Breakout
  gdb_lot_size: 0.01,
  gdb_max_open_trades: 1,
  gdb_max_trades_per_day: 1,
  gdb_risk_reward: 2,
  gdb_sl_buffer_points: 5,
  gdb_breakout_buffer_points: 3,
  gdb_min_range_points: 50,
  gdb_max_range_points: 2000,
  gdb_use_atr_filter: true,
  gdb_atr_period: 14,
  gdb_min_atr: 0,
  gdb_use_break_even: true,
  gdb_break_even_at_r: 1,
  gdb_use_trailing: true,
  gdb_trailing_start_r: 1,
  gdb_trailing_atr_mult: 1.5,
  gdb_cancel_at_session_end: true,
  gdb_max_spread_points: 30,
  gdb_max_daily_loss_pct: 2,
  gdb_equity_stop_pct: 3,
  gdb_max_consecutive_losses: 2,
  gdb_cooldown_hours: 8,
};

// Keys that live only in the form UI — never loaded from or saved to BotSettings.
// strategy = resolved by caller before onStart; dynamic_stop_loss / atr_sl_multiplier / hft_* = form-only state.
export const FORM_ONLY_KEYS = new Set([
  "strategy", "dynamic_stop_loss", "atr_sl_multiplier",
  "hft_max_trades", "hft_burst_points", "hft_basket_tp_pts", "hft_stop_loss_pts",
  "hft_use_break_even", "hft_be_trigger", "hft_be_lock", "hft_trailing_dist",
  "hft_max_spread", "hft_ma_period",
]);

// Fields that are permanently locked ON for account safety.
export const LOCKED_ON = { equity_guard_enabled: true, auto_stop_enabled: true };